import type { WeakArea, WeakAreasResult } from "./weakAreas";

export type SheetGuidance = {
  summary: string;
  sectionsToHighlight: { label: string; reason: string }[];
  annotations: string[];
  difficultyAdjustment: string;
};

function measureList(ms: number[]): string {
  return ms.length === 1 ? `measure ${ms[0]}` : `measures ${ms.join(", ")}`;
}

function annotationFor(a: WeakArea): string {
  if (a.category === "hand") {
    const hand = a.name.toLowerCase();
    return `${a.name}: play it alone, hands separate, before combining. Its ${hand} notes are where most misses land.`;
  }
  if (a.hotMeasures.length > 0) {
    return `${a.name}: slips repeat in ${measureList(a.hotMeasures)}. Loop those first.`;
  }
  return `${a.name}: no single spot repeats yet. Replay it in short sections at a slower tempo.`;
}

function difficultyFor(top: WeakArea): string {
  if (top.priority === "PRIORITY") {
    if (top.category === "lesson" && top.tempoBpm) {
      const lo = Math.round(top.tempoBpm * 0.8);
      const hi = Math.round(top.tempoBpm * 0.85);
      return `Slow ${top.name} down from ${top.tempoBpm} BPM to about ${lo}-${hi} BPM until it is clean twice in a row.`;
    }
    return `Slow down on ${top.name} and drill it alone until it is clean twice in a row.`;
  }
  if (top.priority === "MEDIUM") {
    return "Keep your tempo and loop the trouble spots. Raise it only after two clean passes.";
  }
  return "The gap is small. Keep your tempo and add one extra pass on the marked spots.";
}

/**
 * Turn the ranked weak-areas list into the text shown under the score sketch.
 * Everything here is a rule over real numbers; nothing is generated by the model.
 */
export function buildSheetGuidance(weak: WeakAreasResult, sessionCount: number): SheetGuidance {
  if (weak.isEmpty) {
    if (sessionCount === 0) {
      return {
        summary: "Play a few scored lessons and the spots that need work will be marked here.",
        sectionsToHighlight: [],
        annotations: [],
        difficultyAdjustment: "Nothing to adjust yet.",
      };
    }
    return {
      summary: "No weak spots stand out right now.",
      sectionsToHighlight: [],
      annotations: [],
      difficultyAdjustment:
        "Accuracy is solid. Try raising the tempo by about 4 BPM on your current lesson.",
    };
  }

  const names = weak.areas.map((a) => a.name);
  return {
    summary: `Marked from your ${weak.areas.length} weakest spot${weak.areas.length === 1 ? "" : "s"}: ${names.join(", ")}.`,
    sectionsToHighlight: weak.areas.map((a) => ({
      label: a.name,
      reason: a.issues[0] ?? "",
    })),
    annotations: weak.areas.map(annotationFor),
    difficultyAdjustment: difficultyFor(weak.areas[0]),
  };
}