import type { Metadata } from "next";
import { Inter, Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar";
import { AuthProvider } from "@/utils/Authsegment";
import { LessonsProvider } from "@/utils/userprogress/lessonprogress";
import { AudioProvider } from "@/components/audio/AudioProvider";
// import UnauthUserNavbar from "@/components/navbar2";
import NavbarSwitcher from "@/components/navswitcher";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins  ({ 
  subsets: ['latin'], 
  weight: ['400', '700'], 
  variable: '--font-poppins' });



export const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${inter.variable} ${poppins.variable} ${playfair.variable}`}
      >
        <NavbarSwitcher />
        <main className="w-full">
          <AuthProvider>
            <AudioProvider>
              <LessonsProvider>{children}</LessonsProvider>
            </AudioProvider>
          </AuthProvider>
        </main>

      </body>
    </html>
  );
}
