import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { AuthProvider } from "@/utils/Authsegment";
import { LessonsProvider } from "@/utils/userprogress/lessonprogress";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins  ({ 
  subsets: ['latin'], 
  weight: ['400', '700'], 
  variable: '--font-poppins' });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${inter.variable} ${poppins.variable}`}
      >
        <Navbar/>
        <main className="w-full">
          <AuthProvider>
            <LessonsProvider>{children}</LessonsProvider>
          </AuthProvider>
        </main>

      </body>
    </html>
  );
}
